services:
  - type: web
    name: nft-dashboard-api
    runtime: node
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
